// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Validate configuration
if (!SUPABASE_URL || SUPABASE_URL.includes('your_') || SUPABASE_URL === '') {
  console.error('❌ VITE_SUPABASE_URL não está configurado corretamente no arquivo .env');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('your_') || SUPABASE_PUBLISHABLE_KEY === '') {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY não está configurado corretamente no arquivo .env');
  console.error('📝 Para obter sua chave, acesse: https://app.supabase.com/project/srdmyrwuvuqyzgtsvcjj/settings/api');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});